// This is an autogenerated file from running `firebase genkit:flow`.
'use server';

/**
 * @fileOverview This file defines a Genkit flow for generating personalized conversation starters
 * based on a given profile text. It exports the flow itself, along with its input and output types.
 *
 * - generateConversationStarters - An async function that takes a profile text as input and returns
 *   a list of suggested conversation starters.
 * - GenerateConversationStartersInput - The input type for the generateConversationStarters function.
 * - GenerateConversationStartersOutput - The output type for the generateConversationStarters function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';
import { chatCompletion } from '@/lib/ai-service'; // Import the chatCompletion function from our AI service

const GenerateConversationStartersInputSchema = z.object({
  profileText: z.string().describe('The profile text of the potential match.'),
});

export type GenerateConversationStartersInput = z.infer<
  typeof GenerateConversationStartersInputSchema
>;

const GenerateConversationStartersOutputSchema = z.object({
  conversationStarters: z.array(
    z.string().describe('A personalized conversation starter suggestion.')
  ).describe('A list of suggested conversation starters.'),
});

export type GenerateConversationStartersOutput = z.infer<
  typeof GenerateConversationStartersOutputSchema
>;

export async function generateConversationStarters(
  input: GenerateConversationStartersInput
): Promise<GenerateConversationStartersOutput> {
  return generateConversationStartersFlow(input);
}

const conversationStartersPrompt = ai.definePrompt({
  name: 'conversationStartersPrompt',
  input: {schema: GenerateConversationStartersInputSchema},
  output: {schema: GenerateConversationStartersOutputSchema},
  prompt: `You are a helpful dating assistant. Given the following dating profile text, generate 3-5 personalized and unique conversation starters that are respectful and engaging. The entire response must be in Dutch.

Profile text: {{{profileText}}}

Format the output as a JSON object with a "conversationStarters" field that is an array of strings.`,
});

const generateConversationStartersFlow = ai.defineFlow(
  {
    name: 'generateConversationStartersFlow',
    inputSchema: GenerateConversationStartersInputSchema,
    outputSchema: GenerateConversationStartersOutputSchema,
  },
  async input => {
    // Use our AI service's chatCompletion function which is properly configured for OpenRouter
    const messages = [
      {
        role: 'system' as const,
        content: 'You are a helpful dating assistant. Given the following dating profile text, generate 3-5 personalized and unique conversation starters that are respectful and engaging. The entire response must be in Dutch.'
      },
      {
        role: 'user' as const,
        content: `Profile text: ${input.profileText}\n\nFormat the output as a JSON object with a "conversationStarters" field that is an array of strings.`
      }
    ];
    
    const response = await chatCompletion(messages, {
      provider: 'openrouter',
      maxTokens: 500,
      temperature: 0.7
    });
    
    // Parse the JSON response
    const jsonMatch = response.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      throw new Error('No JSON found in response');
    }
    
    const parsed = JSON.parse(jsonMatch[0]);
    return parsed;
  }
);