/**
 * WORLD-CLASS BLOG TYPE DEFINITIONS
 *
 * Complete TypeScript interfaces for the enhanced blog system.
 * Based on WeAreImpact architecture with DatingAssistent customization.
 *
 * @module types/blog
 * @author DatingAssistent Team
 * @version 2.0.0
 */

// ============================================================================
// BLOG CATEGORIES
// ============================================================================

/**
 * Predefined blog categories aligned with DatingAssistent content pillars
 */
export const BLOG_CATEGORIES = [
  'Daten & Liefde',
  'AI & Technologie',
  'Praktische Gidsen',
  'Inspiratie & Motivatie',
  'Succesverhalen',
  'Online Dating Tips',
] as const;

export type BlogCategory = typeof BLOG_CATEGORIES[number];

/**
 * Check if a string is a valid blog category
 */
export function isValidCategory(category: string): category is BlogCategory {
  return (BLOG_CATEGORIES as readonly string[]).includes(category);
}

// ============================================================================
// HEADER TYPES
// ============================================================================

/**
 * Header display options for blog posts
 * - image: Featured image cover
 * - color: Solid color background with overlay text
 */
export type BlogHeaderType = 'image' | 'color';

/**
 * Header configuration
 */
export interface BlogHeader {
  type: BlogHeaderType;
  // Image header fields
  imageUrl?: string;
  imageAlt?: string;
  imageBlobId?: string;
  // Color header fields
  color?: string;
  title?: string;
}

// ============================================================================
// SEO & SOCIAL MEDIA
// ============================================================================

/**
 * SEO metadata for blog posts
 */
export interface BlogSEO {
  title: string;           // Max 60 characters
  description: string;     // Max 155 characters
  keywords: string[];      // 5-10 keywords
  focusKeyword?: string;   // Primary keyword for optimization
  slug: string;            // URL-friendly identifier
}

/**
 * Social media metadata for blog posts
 */
export interface BlogSocialMedia {
  title: string;           // Max 70 characters (different from SEO)
  description: string;     // Max 200 characters
  imageUrl?: string;       // Open Graph image (1200x630)
  hashtags: string[];      // 3-5 hashtags
  // Platform-specific posts (generated by AI)
  facebookPost?: string;
  twitterPost?: string;    // Max 280 characters
  linkedInPost?: string;
}

// ============================================================================
// AUTHOR
// ============================================================================

/**
 * Blog post author information
 */
export interface BlogAuthor {
  name: string;
  bio?: string;
  avatar?: string;         // URL to avatar image
  email?: string;
}

// ============================================================================
// CONTENT
// ============================================================================

/**
 * Blog content in multiple formats
 */
export interface BlogContent {
  html: string;            // Rendered HTML from TipTap
  json?: Record<string, any>; // TipTap JSON format for editing
  plainText?: string;      // Stripped plain text (for search)
}

/**
 * Content structure analysis
 */
export interface BlogStructure {
  h1?: string;
  h2s: string[];
  h3s: string[];
  wordCount: number;
  paragraphCount: number;
  readingTime: number;     // In minutes
}

// ============================================================================
// PUBLISHING
// ============================================================================

/**
 * Publishing status
 */
export type BlogStatus = 'draft' | 'published' | 'scheduled';

/**
 * Publishing configuration
 */
export interface BlogPublishing {
  status: BlogStatus;
  publishedAt?: Date;
  scheduledFor?: Date;
  isFeatured: boolean;
  allowComments: boolean;
}

// ============================================================================
// ANALYTICS
// ============================================================================

/**
 * Blog post analytics
 */
export interface BlogAnalytics {
  views: number;
  aiOptimizationCount: number;
  lastOptimizedAt?: Date;
  shares?: {
    facebook: number;
    twitter: number;
    linkedin: number;
  };
}

// ============================================================================
// MAIN BLOG POST INTERFACE
// ============================================================================

/**
 * Complete blog post with all enhanced fields
 * Compatible with existing 'blogs' database table
 */
export interface BlogPost {
  // Core fields (existing)
  id: number;
  title: string;
  excerpt: string;
  content: string;          // HTML content
  slug: string;

  // Legacy image field (backward compatibility)
  image?: string;           // Old featured_image field

  // Enhanced image fields (Vercel Blob)
  cover_image_url?: string;
  cover_image_alt?: string;
  cover_image_blob_id?: string;

  // Header configuration
  header_type: BlogHeaderType;
  header_color?: string;
  header_title?: string;

  // Category & Tags
  category: BlogCategory | string;
  tags: string[];
  keywords: string[];       // JSONB array (legacy, prefer tags)

  // SEO fields
  meta_title?: string;      // Legacy field (use seo_title)
  meta_description?: string;// Legacy field (use seo_description)
  seo_title?: string;
  seo_description?: string;

  // Social media
  social_title?: string;
  social_description?: string;

  // Author
  author: string;
  author_bio?: string;
  author_avatar?: string;

  // Content formats
  content_json?: Record<string, any>; // TipTap JSON

  // Publishing
  published: boolean;       // Legacy field
  publish_date?: Date;      // Legacy field
  published_at?: Date;

  // Analytics
  views: number;
  reading_time: number;
  ai_optimization_count: number;
  last_optimized_at?: Date;

  // Timestamps
  created_at: Date;
  updated_at: Date;

  // Misc
  placeholder_text?: string; // For posts without images
  midjourney_prompt?: string;// AI image generation prompt
}

/**
 * Simplified blog post for listing views
 */
export interface BlogPostSummary {
  id: number;
  title: string;
  excerpt: string;
  slug: string;
  category: BlogCategory | string;
  tags: string[];
  cover_image_url?: string;
  placeholder_text?: string;
  header_type: BlogHeaderType;
  header_color?: string;
  author: string;
  reading_time: number;
  views: number;
  published_at?: Date;
  created_at: Date;
}

/**
 * Blog post creation form data
 */
export interface CreateBlogPostData {
  title: string;
  excerpt: string;
  content: string;
  content_json?: Record<string, any>;
  slug: string;
  category: BlogCategory | string;
  tags: string[];

  // Header
  header_type: BlogHeaderType;
  cover_image_url?: string;
  cover_image_alt?: string;
  header_color?: string;
  header_title?: string;

  // SEO
  seo_title?: string;
  seo_description?: string;

  // Social
  social_title?: string;
  social_description?: string;

  // Author
  author?: string;
  author_bio?: string;
  author_avatar?: string;

  // Publishing
  published: boolean;
  published_at?: Date;

  // Analytics
  reading_time?: number;
}

/**
 * Blog post update data (partial update)
 */
export type UpdateBlogPostData = Partial<CreateBlogPostData> & {
  id: number;
};

// ============================================================================
// API RESPONSES
// ============================================================================

/**
 * API response for blog listing
 */
export interface BlogListResponse {
  success: boolean;
  blogs: BlogPostSummary[];
  total: number;
  page: number;
  limit: number;
  hasMore: boolean;
}

/**
 * API response for single blog post
 */
export interface BlogPostResponse {
  success: boolean;
  blog: BlogPost;
  related?: BlogPostSummary[];
  popular?: BlogPostSummary[];
}

/**
 * API response for blog operations (create, update, delete)
 */
export interface BlogOperationResponse {
  success: boolean;
  message: string;
  blog?: BlogPost;
  error?: string;
}

// ============================================================================
// FILTERING & SORTING
// ============================================================================

/**
 * Blog listing filter options
 */
export interface BlogFilters {
  category?: BlogCategory | string;
  tags?: string[];
  search?: string;
  published?: boolean;
  minReadingTime?: number;
  maxReadingTime?: number;
  author?: string;
}

/**
 * Blog sorting options
 */
export type BlogSortBy =
  | 'created_at'
  | 'published_at'
  | 'views'
  | 'reading_time'
  | 'title';

export type BlogSortOrder = 'asc' | 'desc';

export interface BlogSortOptions {
  sortBy: BlogSortBy;
  order: BlogSortOrder;
}

/**
 * Blog listing query parameters
 */
export interface BlogListQuery extends BlogFilters, Partial<BlogSortOptions> {
  page?: number;
  limit?: number;
}

// ============================================================================
// AI OPTIMIZATION
// ============================================================================

/**
 * AI optimization suggestions
 */
export interface BlogOptimizationSuggestions {
  headingStructure: {
    hasH1: boolean;
    h2Count: number;
    h3Count: number;
    recommendation: string;
  };
  keywordDensity: {
    count: number;
    density: number; // percentage
    recommendation: string;
  };
  readability: {
    score: number; // 0-100
    sentenceLength: 'good' | 'too_long' | 'too_short';
    recommendation: string;
  };
  contentLength: {
    wordCount: number;
    recommendation: string;
  };
  improvements: string[];
}

/**
 * AI optimization response
 */
export interface BlogOptimizationResponse {
  success: boolean;
  suggestions: BlogOptimizationSuggestions;
  optimizedContent?: string;
  seoScore?: number; // 0-100
}

/**
 * AI metadata enhancement response
 */
export interface BlogMetadataEnhancementResponse {
  success: boolean;
  seo: {
    title: string;
    description: string;
    keywords: string[];
  };
  social: {
    title: string;
    description: string;
    hashtags: string[];
    facebookPost: string;
    twitterPost: string;
    linkedInPost: string;
  };
}

/**
 * AI blog generation response
 */
export interface BlogGenerationResponse {
  success: boolean;
  title: string;
  content: string;
  excerpt: string;
  slug: string;
  seoTitle: string;
  seoDescription: string;
  socialTitle: string;
  socialDescription: string;
  keywords: string[];
  hashtags: string[];
  category: string;
  readingTime: number;
  headerSuggestion: {
    type: 'image' | 'color';
    colorHex?: string;
    imagePrompt?: string;
    headerTitle?: string;
  };
  midjourneyPrompt?: string;
}

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

/**
 * Calculate reading time based on word count
 * Average reading speed: 200 words per minute
 */
export function calculateReadingTime(content: string): number {
  const words = content.trim().split(/\s+/).length;
  return Math.max(1, Math.ceil(words / 200));
}

/**
 * Generate URL-friendly slug from title
 */
export function generateSlug(title: string): string {
  return title
    .toLowerCase()
    .trim()
    .replace(/[^\w\s-]/g, '') // Remove special characters
    .replace(/\s+/g, '-')     // Replace spaces with hyphens
    .replace(/-+/g, '-')      // Replace multiple hyphens with single
    .substring(0, 100);       // Limit length
}

/**
 * Get display image (prioritize Vercel Blob over legacy)
 */
export function getBlogDisplayImage(blog: BlogPost): string | undefined {
  return blog.cover_image_url || blog.image;
}

/**
 * Check if blog post is published
 */
export function isBlogPublished(blog: BlogPost): boolean {
  if (!blog.published) return false;
  if (blog.published_at && blog.published_at > new Date()) return false;
  return true;
}

/**
 * Get blog post status
 */
export function getBlogStatus(blog: BlogPost): BlogStatus {
  if (!blog.published) return 'draft';
  if (blog.published_at && blog.published_at > new Date()) return 'scheduled';
  return 'published';
}

/**
 * Format blog category for display
 */
export function formatCategory(category: string): string {
  return category
    .split(/[-_]/)
    .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join(' ');
}

/**
 * Get reading time label
 */
export function getReadingTimeLabel(minutes: number): string {
  return `${minutes} min read`;
}

/**
 * Validate SEO title length
 */
export function isValidSEOTitle(title: string): boolean {
  return title.length > 0 && title.length <= 60;
}

/**
 * Validate SEO description length
 */
export function isValidSEODescription(description: string): boolean {
  return description.length > 0 && description.length <= 155;
}

/**
 * Validate social title length
 */
export function isValidSocialTitle(title: string): boolean {
  return title.length > 0 && title.length <= 70;
}

/**
 * Validate social description length
 */
export function isValidSocialDescription(description: string): boolean {
  return description.length > 0 && description.length <= 200;
}
